### ISSUE TITLE
When specifying Kubectl version, sometimes the version check doesn't call Kubectl properly

### ISSUE THREAD

**Issue by StephenMP** [Azure/k8s-bake#28]
We have a k8s-bake step setup as follows:

```
- name: Bake manifests
  id: bake
  uses: azure/k8s-bake@v1
  with:
    renderEngine: kustomize
    kustomizationPath: ./k8s/overlays/${{ github.event.deployment.payload.environment }}
    kubectl-version: 'v1.20.5'
```

The weird issue we are seeing though, is for some of our teams, this step works just fine. When it works, for the version check it's calling `/opt/hostedtoolcache/kubectl/1.20.5/x64/kubectl version --client=true -o json`

However, for some teams it fails and when it fails, it's failing on the version check. When examining the logs, I notice that it's calling `/opt/hostedtoolcache/kubectl/1.20.5/x64 version --client=true -o json` (notice the missing `/kubectl` at the end of the path). The failure message is indicating that the command being executed isn't found (which makes sense because it's not actually calling the Kubectl CLI).

There doesn't seem to be a rhyme or reason either. We first noticed it for a team that was running k8s-bake twice, one after the other; however, another team is noticing when only running k8s-bake once. Other teams are unaffected, but all teams are using the exact same YAML listed above.
