### ISSUE TITLE
RenderEngine kustomize not support HelmChartInflationGenerator (must specify --enable-helm)

### ISSUE THREAD

**Issue by michalkonieczny91** [Azure/k8s-bake#55]
Hi, I'm unable to bake manifsest 
I have `kustomization.yaml` file with content:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

helmChartInflationGenerator:
  - chartName: sealed-secrets
    chartRepoUrl: https://bitnami-labs.github.io/sealed-secrets
    chartVersion: 2.0.2
    releaseName: sealed-secrets
    releaseNamespace: base
    values: ./values.yaml
```
and I'm indicate on it in my action `azure/k8s-bake@v2.1`
```yaml
      - name: Bake deployment SealedSecrets
        uses: azure/k8s-bake@v2.1
        with:
          renderEngine: 'kustomize'
          args: --enable-helm #  I need something like this 
          kustomizationPath: ${{ inputs.KUSTOMIZE_SEALED_SECRETS_PATH }}
          kubectl-version: latest
        id: bake-sealed-secrets
```
but in this step I'm receiving a error 
```
error: accumulating resources: accumulation err='accumulating resources from '../../../base/sealed-secrets': '/home/runner/work/code-iac/code-iac/argocd/iac/base/sealed-secrets' must resolve to a file': recursed accumulation of path '/home/runner/work/code-iac/code-iac/argocd/iac/base/sealed-secrets': trouble configuring builtin HelmChartInflationGenerator with config: `
name: sealed-secrets
releaseName: sealed-secrets
repo: https://bitnami-labs.github.io/sealed-secrets
valuesFile: ./values.yaml
version: 2.0.2
`: must specify --enable-helm
Error: Error: Failed to run bake action. Error: Error: The process '/opt/hostedtoolcache/kubectl/1.23.4/x64/kubectl' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/azure/k8s-bake/v2.1/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (events.js:[31](https://github.com/xxx/runs/5496238727?check_suite_focus=true#step:5:31)4:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
in kustomize I can reproduce it with ommit flag  `--enable-helm` but after I add it to args like this:
`kustomize build --enable-helm . ` it works perfeclty
There is any plan to add this feature?
