### ISSUE TITLE
Show error logs if kustomize fails

### ISSUE THREAD

**Issue by nonylene** [Azure/k8s-bake#59]
I'm using this action to build manifests with Kustomize. 

```yaml
      - uses: azure/k8s-bake@v1
        with:
          renderEngine: 'kustomize'
          kustomizationPath: '...'
          kubectl-version: 'latest'
```

This mostly works well, but I have one problem; I can't see build error logs even if Kustomize fails and have to debug manifests by running `kubectl kustomize` manually.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/7397316/162654848-edeb4361-c517-4029-b108-134bcea32e75.png">

Is there a way to see error logs from Kustomize?
