### ISSUE TITLE
Try to use specific kuebctl-version (v1.27.7)

### ISSUE THREAD

**Issue by J-Are** [Azure/k8s-bake#98]
Hi,
I would like to install and use specific version of kubectl (v1.27.7) in order to fit with the api server of my AKS cluster (that I have upgraded). I use v3 version of k8s-bake.
After reading the metadata file https://github.com/Azure/k8s-bake/blob/main/action.yml, I noticed that kubectl-version parameter is available to "Installs a specific version of kubectl binary" as it is written in the description.

I do not understand why in my GitHub action workflow logs, the kubectl version is still the latest one (v1.30.1) despite my configuration as you can see in the snapshot below:
![image](https://github.com/Azure/k8s-bake/assets/17073117/179aae0b-d144-46a4-92d9-0aac41c3b967)

This is a snippet of my GitHub action workflow:
```     
   -    name: Configure deployment
        uses: azure/k8s-bake@v3
        with:
          renderEngine: 'kustomize'
          kustomizationPath: ${{ inputs.overlay_path }}
          kubectl-version: '1.27.7' # I also tried v1.27.7
        id: bake
```

Please notice I also tried to use v1.27.7 version but the result remains the same.
I have certainly misunderstood something but I dont know what is it.
Thanks in advance for your help
Have a nice day
Regards,
Julien
